### ISSUE TITLE
[BUG] failed to create tenant along with other resources that have reference to the tenant index

### ISSUE THREAD

**Issue by foxlzl** [opensearch-project/terraform-provider-opensearch#37]
### What is the bug?
A new tenant cannot be created along with an index patterns or any resources that have reference to the tenant index. For example, I'm trying to create a new tenant, `test`, as well as an index pattern in this `test` tenant's index. The first deployment will fail due to a crash in this provider. However, when I check from UI, the tenant actually got created but not the index pattern. If I rerun the Terraform plan and apply again, things would work as expected.

When we create a tenant for the first time, we are creating an index for this tenant as well. I found out the failure only happens  when we don't have such tenant index. Right now, the provider won't delete the tenant index even if we use it to destroy the created tenant. As long as this index remains, we won't see the same failure again for this particular tenant name.

### How can one reproduce the bug?
1. make sure Opensearch does not have any index for a tenant
2. use this provider to create a tenant along with an index pattern assigned to this tenant's index
3. the deployment will fail with the following stack trace
4. If we rerun terraform plan and apply again, we won't see the error, as the new tenant's index already exists.

│   61: resource "opensearch_dashboard_object" "index_patterns" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

Stack trace from the terraform-provider-opensearch_v1.0.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xef475a]
goroutine 147 [running]:
github.com/opensearch-project/terraform-provider-opensearch/provider.elastic7CreateIndexIfNotExists(0xc00052ee00, {0xc00076f980, 0x15}, {0xc00076f980, 0x15})
	github.com/opensearch-project/terraform-provider-opensearch/provider/resource_opensearch_dashboard_object.go:141 +0x21a
github.com/opensearch-project/terraform-provider-opensearch/provider.resourceOpensearchDashboardObjectCreate(0xc0003fe600, {0xf84780?, 0xc000507400})
	github.com/opensearch-project/terraform-provider-opensearch/provider/resource_opensearch_dashboard_object.go:100 +0x10f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x14565e8?, {0x14565e8?, 0xc0005366c0?}, 0xd?, {0xf84780?, 0xc000507400?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:330 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00018b340, {0x14565e8, 0xc0005366c0}, 0xc00062b790, 0xc0003fe480, {0xf84780, 0xc000507400})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000438798, {0x1456540?, 0xc0004eb000?}, 0xc00040d2c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f5c20, {0x14565e8?, 0xc000525ec0?}, 0xc0001f60e0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x111a540?, 0xc0003f5c20}, {0x14565e8, 0xc000525ec0}, 0xc000467a40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000170a80, {0x1459[308](https://gitlab.com/e3803/sre/logging/opensearch-configs/-/jobs/4144544756#L308), 0xc000445a00}, 0xc0008b70e0, 0xc00043b290, 0x1bdfee0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000170a80, {0x1459308, 0xc000445a00}, 0xc0008b70e0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
Error: The terraform-provider-opensearch_v1.0.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### What is the expected behavior?
A brand new tenant should be able to get created along with an index pattern or any other resources that has reference to the tenant's index.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by rishabh6788** [comment]
@opensearch-project/opensearch-dashboards-core Could you please advise if this is a known issue from dashboards side?

**Comment by ashwin-pc** [comment]
Yes, a index pattern cannot be created before an index with that pattern exists. Why are we trying to create an index pattern before the index itself?

**Comment by foxlzl** [comment]
Maybe the title of this bug is not clear. The point here is when we try to create an index pattern before the index, the index gets created but the index pattern creation fails. It seems like this use case, creating index pattern for a nonexistent index, is supposed to work but fails actually, otherwise the index won't be created at all, since I didn't explicitly create it.
